name: Gradle Setup

on:
  workflow_call:
    inputs:
      gradle-task:
        required: true
        type: string

jobs:
  run:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6.0.3

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24

      - uses: gradle/actions/setup-gradle@v6.1.0

      - run: ./gradlew ${{ inputs.gradle-task }}